### ISSUE TITLE
Specify different recipients for different messages

### ISSUE THREAD

**Issue by joekerna** [bbernhard/signal-homeassistant#1]
Is it possible to add a recipient to a specific message?
For example:

On sunrise send message "Sunrise" to +49123456
On sunset send message "Sunset" to +49654321

**Comment by bbernhard** [comment]
First of all: I've recently added the signal messenger integration to Home Assistant (see: https://www.home-assistant.io/integrations/signal_messenger/). So it's now an official Home Assistant integration - i.e the custom component is not needed (and also not maintained) anymore. So, if you are still using the custom component, I would highly recommend you to migrate your setup to the official integration - that's the only one that is maintained. 

regarding your question: Unfortunately, that's not possible (not even with the official integration). Does it maybe work, if you are moving the logic to Home Assistant?

I haven't tried it yet, but I think it should be possible to define multiple integrations of the same type with different names. So you could define two signal messenger instances with different recipients. 

e.g something like that: 

```
notify:
  - name: signal1
    platform: signal_messenger
    url: "http://127.0.0.1:8080" # the URL where the Signal Messenger REST API is listening
    number: "YOUR_PHONE_NUMBER" # the sender number
    recipients: # one or more recipients
      - "+49123456"
  - name: signal2
    platform: signal_messenger
    url: "http://127.0.0.1:8080" # the URL where the Signal Messenger REST API is listening
    number: "YOUR_PHONE_NUMBER" # the sender number
    recipients: # one or more recipients
      - "+49654321"
```

And inside your Home Assistant logic you either use the first instance (`signal1`) or the second instance (`signal2`), depending to whom you want to send the message to.
